### ISSUE TITLE
Changing folder names

### ISSUE THREAD

**Issue by jlgarnier** [rishikeshgaikar/vscode-react-native-boilerplate#2]
Hi Rishikesh!

This is not an issue but I couldn't find another place to ask about this... I'd like to use your great extension but would like to slightly change some folder names to comply with our coding rules: where can I do this without breaking the ext?

Thanks in advance for your support!

**Comment by rishikeshgaikar** [comment]
There is no such functionality as of now. But you can easily change it in data.js file under scripts folder. If you are using different file structure post it here, I will try to include that in upcoming update. Lets connect on [Twitter](https://twitter.com/rishikeshgaikar) to discuss further.

**Comment by jlgarnier** [comment]
Thanks a lot for this quick answer! I'll go for adapting the source code, as I just need to rename some folders or files (i.e. Scenes --> Views) and redistribute the extension to colleagues... Thanks again and keep up the good work!
